jareff-g/ALT-Scann8

ALT-Scann8-Controller.ino, ALT-Scann8-UserInterface.py
This commit contains the removal of the adjustable reference hole marker. Replaced by new hardcoded markers, one for S8, another for R8. Also includes a fix for a typo in the Arduino code, not sure how it did  get there.
=> Hardcode hole marker

ALT-Scann8-UserInterface.py
(should have been done before the merge, still getting used to git :-<)
=> Final adjustments for the position of the reference holes for R8

.idea/ALT-Scann8.iml, ALT-Scann8-UserInterface.py
Change legacy widgets using buttons and text boxes to spinboxes, to have a more homogeneous UI
=> UI Homogenisation

ALT-Scann8-Controller.ino
- Scan function is now activated more frequently, advancing a single step each loop (vs 5 before)
- Frame detection slowdown is relaxed, before it was more conservative, but it did not help to keep the frame more stable
- PT threshold ratio is reduced from 30 to 20, otherwise frame was advancing too much
=> - Several changes in the way scan function works:

ALT-Scann8-Controller.ino, ALT-Scann8-Pico-Controller.c, ALT-Scann8-UserInterface.py
- Added experimental item to perform manual scan, frame by frame, manually aligning each
- Bugfix: Problems with manual exposure setting (discovered while working in the manual scan feature)
- Bugfix: Added try statement when sending command to Arduino
- Bugfix: PTLevel an dSteps per frame not retrieved correctly from config file when film is R8
- Removed unused code (sharpness up/down)
=> Manual scan feature (in experimental area)

ALT-Scann8-Controller.ino, ALT-Scann8-Pico-Controller.c, ALT-Scann8-UserInterface.py
- It was removed some weeks ago, due to speed concerns. Now it is reintroduced, linked to the 'Scan speed value', actually bringing more accuracy in frame positioning at lower speeds.
- Bugfix: Better handling of situation when a 'next frame' command (ore response) is lost due to I2C error.
- Bugfix: Take up spool speed better adapts tpo changes in scan speed (specially from lower to higher speed)
=> Reintroduced speed slowdown prior to frame detection

ALT-Scann8-Controller.ino, ALT-Scann8-Pico-Controller.c, ALT-Scann8-UserInterface.py
- Added integrated plotter to allow tuning the photo-transistor height without using Arduino IDE. Use only when required as it slows down processing (due to additional traffic omn I2C bus). Activated via command line (-p)
- Increased speed of I2C bus to 400KHz (but doesn't really help)
- Added command to reset arduino when loading UI
- Removed some redundant 'wire.begin' calls in Arduino
- Added yet another attempt at having better film take up algorythm (not used yet)
=> Integrated plotter

ALT-Scann8-Controller.ino, ALT-Scann8-Pico-Controller.c
Yet another attempt at having a good film take-up algorithm. This time it is simpler, lets see how it behaves.
=> New film take-up algorithm

ALT-Scann8-Controller.ino, ALT-Scann8-Pico-Controller.c, ALT-Scann8-UserInterface.py
- Added end of film detection to automatically stop scan process
=> Scan auto stop

ALT-Scann8-UserInterface.py
- Move focus control buttons to the right of 'Focus Zoom' button
- Technical: Change tkinter widget distribution in expert area from pack to grid to allow redistribution fo widgets
- Added dynamic maximum photo-transistor value to integrated plotter
- Create new area with controls to adjust multi-exposure parameters. All these parameters can be changed at any time during the scan (except the 'Activate' checkbox)
- Active: Enables multi-exposure capture (replaces the 'HDR On' button)
- View x 4: Display preview with all 4 exposures, instead of second frame of each set (to facilitate adjustment of exposure bracket with teh controls below)
- Min exp: Lower exposure in the bracket
- Man exp: Higher exposure in the bracket
- Adjust bracket: Arrange exposure range relative to camera detected …
=> ALT-Scann8 - HDR changes

ALT-Scann8-UserInterface.py
Make required modifications until all issues raised by pyflakes3 resolved
=> Bugfix: Checked UI code againt pyflakes rules

ALT-Scann8-UserInterface.py
- Homogenize captured frames filenames, to allow hybrid capture. First frame in a set always named 'picture-nnnnn.jpg', additional hdr frames (if enabled) named picture-nnnnn.x.jpeg (x=2|3|4)
- Adapt level of some logging statements
- Stop scan session if target drive is unmounted while scanning
=> ALT-Scann8 1.8.3

ALT-Scann8-UserInterface.py
- Automatic multi-exposure bracket adjustment: Exposure bracket calculated every 8 frames based on the automatic exposure value reported by the camera
- Homogenize activation of automatic adjustment in several widgets (steps/frame, PT Level, multi-exposure bracket). Now activatino doen via button or checkbox, instead of the non-standard double-click on edit box used before
- Persist to disk all three bracket parameters
- Factorized similar code used by several widgets
- All three exposure bracket values (min, max, width) recalculated when one of them is modified, so they stay consistent
- Force multi-exposure dry run shoots when bracket parameters change
- Changed mouse-over widget background color (to make it more discret)
- Smaller widget box for speed/stabilization delay
=> Automatic calculation of exposure bracket

ALT-Scann8-UserInterface.py
- Change HDR exposure calculation algorithm so that the automatically detected exposure is in the middle of the bracket (as long as possible). In the case of 5 exposures the extra 2 are added in the middle of each segment.
- Persist frames-to-go setting between sessions
- Prevent error in case non-number characters are typed in the frames-to-go entry
- In debug mode, do not log IOError 121 (happens when there is no data available from Arduino, which is usually a normal condition)
=> ALT-Scann8 1.8.11 - New HDR exposure bracket calculation

ALT-Scann8-UserInterface.py
ALT-Scann8 v1.8.15
Main changes: Removal of code supporting PiCamera legacy, plus a couple of changes to make the real-time view feature more accurate (same view as the actual capture, plus zoom now can reach the very border of the image)
=> Picamera legacy removal

ALT-Scann8-UserInterface.py, tooltip.py
=> ALT-Scann8 1.8.30

ALT-Scann8-Controller.ino, ALT-Scann8-Pico-Controller.ino, ALT-Scann8-UserInterface.py
Allow captures to be saved as PNG (slower than JPG)
Adapted timings in UI and Arduino to allow slower scans (otherwise end of reel was being notified while scanning)
When using PNG + HQ + HDR scan speed can be as slow as 4 FPM (vs 160 FPM for a single exposure scan in JPG using standard resolution).
=> Png option

ALT-Scann8-Controller.ino, ALT-Scann8-UserInterface.py
Arduino 1.0.2
- Auto-stop at end of reel when doing film forward (not yet working)
- Bugfix: While scanning, sometimes an extra snapshot was taken whiel the film was moving. This is nto corrected
ALT-Scann8 1.8.33
- Improved some logging
- Add 'video time' in current frame box
- Prevent drawing in the top 15 pixels of plotter area
- Better adjust of R8 hole markers
- Bugfix: Add fixed margin (20%) to auto PT level to prevent frame skipping when 'fine tune' is set to the minimum
- Bugfix: Scan process terminated when delay due to skipped Arduino command was too long
=> Bugfixes and minor changes

ALT-Scann8-UserInterface.py
- Allow shifting the HDR bracket +/-100ms from the default position (determined by automatic exposure). Values displayed in the UI do not change, the shift is applied on them only when setting the exposure to th e camera.
- Parametrize row indicator in HDR area in the UI
=> ALT-Scann8 1.8.34 - HDR Bracket Shift

ALT-Scann8-UserInterface.py
- Harmonize handling of labels in 'Scanned frames' box. Instead of updating the widget text, use a linked variable.
=> ALT-Scann8 1.8.35 - Harmonize Scanned frames labels

ALT-Scann8-UserInterface.py
- Harmonize handling of labels in 'Scanned frames' box. Instead of updating the widget text, use a linked variable.
=> ALT-Scann8 1.8.35 (#52)

ALT-Scann8-UserInterface.py
* ALT-Scann8 1.8.34 (#51)
- Allow shifting the HDR bracket +/-100ms from the default position (determined by automatic exposure). Values displayed in the UI do not change, the shift is applied on them only when setting the exposure to th e camera.
* ALT-Scann8 1.8.34
- Implement Mertens merge option. The idea is to optimize process so that while we are waiting for the camera to adapt exposures, the frame processing threads are doing the Mertens merge of captured images (so that only the merged one will be saved to disk, saving some time in post-processing)
- Adapt share idle timer in RPi Arduino so that RPi only waits 1/3rd of the total time (to avoid false end-of reel detection)
* ALT-Scann8 1.8.35 (#52) (#53)
- Harmonize handling of labels in 'Scanned frames' box. Instead of updating …
=> Merge in place (#54)

ALT-Scann8-UserInterface.py
Update latest changes in develop to mertens merge branch
=> Merge Develop with merge_in_place

ALT-Scann8-UserInterface.py
- HDR merge-in-place now works. But, as anticipated, is too slow (around 11 FPM, vs 36 FPM without). Rough extrapolation for RPi5 (x2.5 RPi4) would be 27 FPM, faster but still slow
=> ALT-Scann8 1.8.40

ALT-Scann8-UserInterface.py
- HDR merge-in-place now works. But, as anticipated, is too slow (around 11 FPM, vs 36 FPM without). Rough extrapolation for RPi5 (x2.5 RPi4) would be 27 FPM, faster but still slow
=> ALT-Scann8 1.8.40 (#59) - Merge-in-place working, but very slow

ALT-Scann8-UserInterface.py
- Review of alignment of widgets, make them more evenly distributed, also in small screen mode
=> ALT-Scann8 1.8.41 - UI widget alignment

ALT-Scann8-UserInterface.py
- Fix some remaining alignment issues
- Display popup warning when running out of disk space
- Add disk space check to simulated capture loop (to test new popup)
=> ALT-Scann8 1.8.42 - Bugfixes

ALT-Scann8-UserInterface.py
- Errors when starting in experimental or expert mode alone (only working when using both together)
=> ALT-Scann8 1.8.43

ALT-Scann8-Controller.ino, ALT-Scann8-UserInterface.py
- Add threshold level to integrated plotter
- Disable merge in place checkbox when hdr is disabled
=> Plotter threshold

ALT-Scann8-Controller.ino
Arduino 1.0.6:
- Fix bug when adjusting dynamic min/max levels in GetLevelPT
=> ALT-Scann8 1.9.1

README.md
=> Align develop with master 

ALT-Scann8-Controller.ino, ALT-Scann8-Pico-Controller.ino, ALT-Scann8-UserInterface.py, README.md
- Automatic stop is now disabled by default, it can be enabled via checkbox
- 'Negative film' button works again
=> ALT-Scann8 - Bug fixes and Minor UI changes

ALT-Scann8-Controller.ino, ALT-Scann8-UserInterface.py
Several bugfixes, new algorithm to detect end if reel (hopefully this one will be more general) and popup warning added when selecting an existing folder as target, and the last captured frame indicated after folder selection implies overwriting existing files.
=> ALT-Scann8 .1.9.3 / Arduino 1.0.9:

ALT-Scann8-UserInterface.py
- Added button for UI mode toggle
- fix for error when selecting auto AWB while scanning
=> Dynamic UI change (full UI vs reduced)

ALT-Scann8-UserInterface.py
- Changed implementation of toggle UI button. Thi stime I picked the easy way
=> ALT-Scann8 1.9.9

ALT-Scann8-UserInterface.py
- Use alternate method to get script folder
- Disable AWB on the camera upon initialization
- Remove conversion when reading NegativeCaptureActive
- Expert mode, experimental mode and plotter are enabled by default now
- Remove log when receiving plotter data
- Fix glitch whe closing preview window with the top right X button
=> ALT-Scann8 1.9.12

ALT-Scann8-UserInterface.py
- Bugfix: Sharpness value was handled by the UI but never set at cammera level, except at init time (so always 1)
=> ALT-Scann8 1.9.12 - Fix Sharpness

ALT-Scann8-UserInterface.py
- Fix: Freeze after start scanning
=> ALT-Scann8 1.9.21

ALT-Scann8-Controller.ino, ALT-Scann8-UserInterface.py
- Arduino Fix: Automatic frame steps was broken on Arduino
- ALT-Scann8: Add DNG support
- Add command line option (-t) to disable multithreading
=> ALT-Scann8 1.9.22

ALT-Scann8-UserInterface.py
- Bugfix: Make the HDR min/max exposure fields green when automatic mode enabled
- Add curly bracket to join the two WB channels towards common checkboxes
- Remove useless attributes from some frames
=> ALT-Scann8 1.9.24

ALT-Scann8-UserInterface.py
- Create class to handle camera resolutions and associated info (resolutions not hardcoded anymore, but retrieved from picamera2)
- Initialize PiCamera2 before creating UI (to have camera resolutions to populate drop down)
- Added two extra resolutions (1024x769, 640x480), using the fastest sensor resolution (1332x 990). As a result, scanning is slightly faster, but both require readjusting the lens zoom.
- Set default log level to INFO
- Factorize field validation functions
- Allow tab/backtab on read-only spinboxes
- Create simulated_sensor_modes (replicating answer from HD camera)
- Cancel outsanding afters upon exit (to avoid 2 sec delay on exit)
-  Added code to exit app cleanly (waiting for threads to end)
=> ALT-Scann8 1.9.25 - Clean up capture resolutions

ALT-Scann8-UserInterface.py, tooltip.py
- Flag cropped capture resolutions with asterisk, adn add note in tooltip about lens adjustment required for them
- Update tooltips to latest version
- Do not wait for threads to end in simulated run
- Optimize process when saving file. Use PiCamera2 request to  save file in all cases as it is faster. When negative image is selected image is saved via PIL as modification is required.
- Limit exposure range:  Values from 0 to 1 second allowed (in milliseconds)
=> ALT-Scann8 1.9.27

ALT-Scann8-UserInterface.py
=> ALT-Scann8 1.9.28

ALT-Scann8-UserInterface.py, camera_resolutions.py, dynamic_spinbox.py, tooltip.py
- Convert tooltip.py module to class, keep it in separate file
- Move two existing classes (DynamicSpinbox, CameraResolutions) to dedicated files
=> ALT-Scann8 - Move 3 classes to dedicated files

ALT-Scann8-UserInterface.py, rolling_average.py
- Added new clas to calculate rolling averages for 4 values:
- Time to save frame
- Time to display preview
- Time waiting for Auto exposure
- Time waiting for Auto WB
=> ALT-Scann8 1.9.31

ALT-Scann8-UserInterface.py
- Command line switches -e, -x and -p toggle the defautl state of those three items
=> ALT-Scann8 1.9.32

ALT-Scann8-UserInterface.py
- Fix error when creating IntVars for stats
- When switching AEC/AWC on and off, do not retrieve current values from camera, as if could conflict with ongoign scan processes
- Change capture process so that image is saved from PiCamera2 capture whenever possible (all cases except negative image).
- Add save time stats in a couple of places where it was missing
=> ALT-Scann8 1.9.34

ALT-Scann8-UserInterface.py
- Change default value of auto PT level and auto frame steps to True
- Enable focus zoom controls when not in expert mode
- Fix 'Toggle UI' button behavior
- Code cleanup: Remove unnecessary global variables
- Display sprocket hole references also when not in  expert mode
- Remove checking 'ExpertMode' if Expert mode widgets, as it is not really needed (if widget is not displayed, comman dwill not be invoked)
- Readjust widget positions
- In HDR mode, pass to encoding threads images instead of PiCamera requests
- Center extended area at the bottom
=> ALT-Scann8 1.9.37

ALT-Scann8-UserInterface.py
- Take into account when AE/AWB are disabled for statistics
- Add control for preview module (to modulate the preview refresh rate from 1:1 to 1:50)
=> ALT-Scann8 1.10.1

ALT-Scann8-UserInterface.py
=> ALT-Scann8 1.10.2

ALT-Scann8-UserInterface.py
- Bugfix: 'AWB Mode' control was enabled/disabled based on AE, instead of AWB. Corrected.
=> ALT-Scann8 1.10.15

ALT-Scann8-UserInterface.py
- Automatic calculation of font size depending on screen size
=> ALT-Scann8 1.10.16

ALT-Scann8-UserInterface.py
- Bugfix: 'AWB Mode' control was enabled/disabled based on AE, instead of AWB. Corrected.
- Automatic calculation of font size depending on screen size
- Keep manual WB values separated from AWB calculated ones
- Control widgets enabled while scanning by default. Opposite behavior with -w
- Refresh AE/AWB values as per 'preview module' setting
- Enforce preview module in all use cases
=> ALT-Scann8 1.10.17 - AWB fixes

ALT-Scann8-UserInterface.py
- Reformat code - Cut lines longer than 120 chars
- Error when starting without reloading configuration in simulated mode
- Set 2028x1520 as default resolution
- Set S8 by default
- In miscellaneous area, add emergency exit button (exit without saving configuration)
- Fix errors when disabling expert and/or plotter modes
- Display error popoup if film type not set
=> ALT-Scann8 1.10.21

ALT-Scann8-UserInterface.py, tooltip.py
- Add options popup (to set most command line options)
=> ALT-Scann 1.10.23 - Add options menu

ALT-Scann8-UserInterface.py
- Add log level to settings popup
=> ALT-Scann8 1.10.24

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, README.md
Templates for bug report and feature, and typo corrected in readme file
=> Merge changes in Master to develop

ALT-Scann8-Controller.ino, ALT-Scann8-UserInterface.py
- widget_list_update: Proceed only if requested widget category exists in dictionary (required when disabling expert/experimental modes)
- Minimize settings popup when selecting home folder, to prevent it hides folder selection dialog
- When Expert mode is disabled, arrange settings:
- Exposure = Auto
- WB = Auto
- Steps per frame = Auto
- PT level = Auto
- Frame fine tune = 20
- Scan speed = 5
- Arduino 1.0.21:
- Make auto PT level range wider (10-90% instead of 20-80%)
- Increase speed of film forward function (film backward left as is since it requires manual intervention)
- Reduce frequency of take-up reel when doing slow forward
- Add command to adjust MinFrameSteps based on capstan diameter (which can now be entered in the settings popup)
- Rearrange/rename 'Scanned Frames' and …
=> ALT-Scann8 1.10.46

ALT-Scann8-UserInterface.py
- QR code Fixes (RPI uses diferent version of PIL)
- Add library versions to QR code
- Display popup with QR info when clicking on QR code
- Fixed return to manual exposure when disabling AE
=> ALT-Scann8 1.10.53

ALT-Scann8-UserInterface.py
- Reshuffle some existing frames to allow making QR code bigger
=> ALT-Scann8 1.10.54

ALT-Scann8-UserInterface.py, hw_panel.py
- Fix issue while switching from automatic exposure to manual
- Fix issue when disabling debug mode in simplified UI
- Add simple api for hardware panels
=> ALT-Scann8 1.10.55

ALT-Scann8-Controller.ino, ALT-Scann8-UserInterface.py
- Add new control to allow setting UV led brightness
=> ALT-Scann8 1.10.59

ALT-Scann8-Controller.ino, ALT-Scann8-UserInterface.py
- Add new button to allow manual activation of plotter (to allow PT/UV led adjustment)
=> ALT-Scann8 1.10.60

ALT-Scann8-Controller.ino, ALT-Scann8-UserInterface.py
- Change in Arduino controller 1.0.25: New algorythm to control scanner speed (no big improvements, only a small speed increase overall)
- Bugfix in UI 1.10.64: Match Margin spinbox was grayed out on startup when checkbox was selected
=> Scan speed bugfix

ALT-Scann8-Controller.ino
Change date in controller file
=> Update date in controller file

ALT-Scann8-UserInterface.py
- Upon first run, without config file, initialize resolution to 2048x1520
- Handle capstan diameter properly (as float, also in spinbox)
=> Fix a couple of bugs

ALT-Scann8-UserInterface.py
Fix issue with settings when starting for the very first time: Retrieve base folder differently
=> Settings not properly saved when starting for the very first time

ALT-Scann8-UserInterface.py
It seems that PiCamera2 QT preview window is changing the LC_NUMERIC locale to be the same as the LANG locale, which is causing the floating point problem when the LANG locale uses a comma for the decimal separator. Apparently by default in python the LC_NUMERIC locale is not set, which defaults to use always a dot for decimal separator in any language. So, to resolve this, the value of LC_LOCALE is saved at program startup, and restored each time the preview window in closed.
=> Fixed problem with floating point spinboxes after activating preview window

ALT-Scann8-Controller.ino
Removed redundant code, improve auto framesteps calculation.
Slowness issue still not found.
=> ALT-Scann-Controller 1.0.29

ALT-Scann8-UserInterface.py
Keep AE/AWB value when switching to manual
=> ALT-Scann8-UserInterface 1.10.71

ALT-Scann8-Controller.ino, ALT-Scann8-UserInterface.py, camera_resolutions.py
Merge latest changes to hwpanel code
=> Develop merge to hwpanel

ALT-Scann8-UserInterface.py
Fix Auto-Stop radio buttons UI: Not disabled when checkbox disabled after changing selected radio button
=> ALT-Scann8 User Interface 1.10.72

ALT-Scann8-UserInterface.py
Fixed zoom view issues:
- View not fully restored after zoom disabled
- UI status (focus + zoom buttons) not properly restored if focus view closed using window close button ('X')
=> ALT-Scann8 User Interface 1.10.73

ALT-Scann8-UserInterface.py
Various fixes:
- Remove wrong command assigned to font size and capstan diameter boxed in settings popup
- Set auto exposur eenabled when startign for the first time (no config file)
- If Auto exposure not enabled in configuration file, start with manual exposure settings
- When starting for the first time, autostop should be disabled, an doptions grayed out
=> ALT-Scann8 user interface 1.10.74

ALT-Scann8-Controller.ino
Improve frame synchronization, specially for first frame (before it was taking up to 5 frames, now only one maximum)
=> ALT-Scann8 controller 1.1.0

ALT-Scann8-UserInterface.py
Fixed scan process slowdown issue. Root cause was the integrated plotter, that was refreshed inside the Arduino loop, and was too heavy for the available time slice. To avoid the issue, the integrated plotter is updated differently (rolling instead of scrolling display) so that it can be managed within the available tile slice. Also, by clicking on the integrated plotter window, the plotter cna be disabled entirely, or even reverted back to the scrolling, heavy version if whished (but the slowdown problem will happen for sure).
=> ALT-Scann8 User Interface 1.11.1

ALT-Scann8-UserInterface.py
Fixed scan process slowdown issue. Root cause was the integrated plotter, that was refreshed inside the Arduino loop, and was too heavy for the available time slice. To avoid the issue, the integrated plotter is updated differently (rolling instead of scrolling display) so that it can be managed within the available tile slice. Also, by clicking on the integrated plotter window, the plotter can be disabled entirely, or even reverted back to the scrolling, heavy version if wished (but the slowdown problem will happen for sure).
=> Investigate speed issue

ALT-Scann8-Controller.ino, ALT-Scann8-UserInterface.py
- Add vertical bar to signal progress of rolling plotter
- When clicking on 'Stop Scan' button, terminate process properly (before Arduino was stopping in frame detection error)
=> ALT-Scann8 user interface v1.11.2, Controller v 1.1.1

ALT-Scann8-Controller.ino, ALT-Scann8-UserInterface.py
Change response to controller command CMD_VERSION_ID, previously returning only controller type (Nano or Pico), to return controller version as well.
=> ALT-Scann8 User interface 1.11.3, Controller 1.1.2

ALT-Scann8-UserInterface.py
- Display text box to replace QR code if QR library not loaded
- Display controller version in main window title
- Add debug info in QR code to log file
=> ALT-Scann8 User Interface 1.11.4

ALT-Scann8-UserInterface.py
* Replace scan errors entry by label, as no user input is required. Also add % of errors
=> ALT-Scann8 User interface 1.11.6

ALT-Scann8-Controller.ino, ALT-Scann8-UserInterface.py
* Scan errors: Count errors only when frame not detected after 2X the number of regular steps
* Disable 'extra steps' checkbox when steps/frame set to manual
=> * ALT-Scann8 User interface 1.11.7, Controller 1.1.4

ALT-Scann8-Controller.ino, ALT-Scann8-UserInterface.py
* Scan errors: Count errors only when frame not detected after 2X the number of regular steps
* Disable 'extra steps' checkbox when steps/frame set to manual
=> ALT-Scann8 User interface 1.11.7, Controller 1.1.4

ALT-Scann8-Controller.ino, ALT-Scann8-UserInterface.py
* Add misaligned frame errors using OpenCV (enabled by default, can be disabled)
* Keep fixed scale in plotter window (to better track evolution)
* Controller to report PT level upon detect frame message (debug purpose)
=> ALT-Scann8 User Interface 1.11.8, Controller 1.1.5

ALT-Scann8-UserInterface.py
* Move 'scan errors' counter to Frame align section, also rename to 'frame errors'
=> ALT-Scann8 User Interface 1.11.9

ALT-Scann8-UserInterface.py
* Change width taken by some widgets to prevent lower control area to be wider than upper
=> ALT-Scann8 User Interface 1.11.10

ALT-Scann8-UserInterface.py
* For existing config files, transform legacy name 'CentreWeighted' to 'CentreWgt'
=> ALT-Scann8 User Interface 1.11.11

ALT-Scann8-UserInterface.py
* Remove test data from UI after latest changes
=> ALT-Scann8 User Interface 1.11.12

ALT-Scann8-UserInterface.py
* Check frame misalignment also in DNG files (**Untested**)
* This feature requires a couple of libraries (rawpy, imageio) which have to be installed via pip, which I prefer not to do in my system. If you give it a try and it works, let me know and I'll remove the warning.
* Fix bug when initializing widget when HDR Auto bracket enabled
=> ALT-Scann8 User Interface 1.11.13

FrameAlignmentChecker.py
* For misaligned frames, display number of pixels by which target is missed (to asses severity)
* Display process duration when done
* Scroll to bottom of text box while process is ongoing
* Prefent user from typign in results test box
=> FrameAlignmentChecker 1.0.1

FrameAlignmentChecker.py
* Optimize frame misalignment detecion by slicing the image before doing the binary threshold
=> FrameAlignmentChecker 1.0.2

FrameAlignmentChecker.py
* Persist generated info in log file (dedicated directory)
* Deal with borderline cases when detecting frame
* Allow clicking on text box to display reported image
* Clean program termination (no errors)
* Cleaner program structure (using main function)
=> FrameAlignmentChecker 1.0.3

ALT-Scann8-UserInterface.py
* Integrate latest version of is_frame_centered function, same as in FrameAlignmentCheck
=> ALT-Scann8 User Interface 1.11.15

ALT-Scann8-UserInterface.py
* Fix freeze when capturing to JPG with frame misalignment detection enabled
* Add exception hook to capture unexpected exceptions to log file
* Fix bug in settings popup: Some settings (file type, frame alignment check) were not properly handled
=> ALT-Scann8 User Interface 1.11.18

ALT-Scann8-UserInterface.py
- Fix remaining bug in settings popup: Setting base folder should not affect target folder in use, only when selecting new one
=> ALT-Scann8 User Interface 1.11.19

ALT-Scann8-UserInterface.py
* Adjust font size of 'Frame Errors' label
* Tune behavior of 'Existing' button on first start (start from base folder)
* Fix widget status issue for all 5 widgets related to frame misalignment detection
=> ALT-Scann8 User Interface 1.11.20

ALT-Scann8-UserInterface.py
* Move misaligned frame detection checkbox to main UI
=> ALT-Scann8 User Interface 1.11.22

ALT-Scann8-UserInterface.py
* Fix behavior of Base Folder/'Existing' button upon first run
=> ALT-Scann8 User Interface 1.11.23

ALT-Scann8-UserInterface.py
* Fix focus view issue (capture resolution changes after focus view enabled)
=> ALT-Scann8 User Interface 1.11.24

ALT-Scann8-UserInterface.py
* Few bugfixes (exceptions due to referencing unaccesible widgets)
=> ALT-Scann8 User Interface 1.12.01

ALT-Scann8-Controller.ino, ALT-Scann8-UserInterface.py
* Remove unused code
* Update 'Capture info' label from the start. At startup, with default values, or those loaded from file, also after changing values in settings.
* If numpy not installed, and error message is displayed and ALT-Scann8 will exit (since numpy is mandatory)
* Ligth UI rearrange. Move 'Exit (do not save)' on top of 'Exit' (to prevent accidental clicks) and change caption of FF/Rwnd/fwd/back buttons to prevent they are interpreted as main controls of ALT-Scann8
* Adjust window size calculation to latest UI changes
* Fix issue when saving PNG in 'manual scan' mode
ALT-Scann8 Controller 1.1.6
* Add new function to collect outgoing film when using manual scan
=> ALT-Scann8 User Interface 1.12.02, ALT-Scann8 Controller 1.1.6

ALT-Scann8-UserInterface.py
* Fix two minor bugs reported on 1.12.02
=> ALT-Scann8 User Interface 1.12.03

ALT-Scann8.py
* Move UUID and user content inside configuration, two dedicated files migrated (but not deleted) if they exist
=> ALT-Scann8 UI 1.12.8

ALT-Scann8.py
* Fix error while waiting for steps confirmation in VisualDetect mode
* New optimized algorithm to detect if frame centered
* Remove is_frame_in_file_centered (was added for DNG, not used now due to Rawpi)
* Fix bug in controller version check
=> ALT-Scann8 UI 1.12.10

ALT-Scann8.py
=> ALT-Scann8 UI 1.12.11

ALT-Scann8.py
* Workaround for possible but in tkinter filedialog.askdirectory
=> ALT-Scann8 UI 1.12.12

ALT-Scann8.py
* Save settings also when clicking on settings/OK
=> ALT-Scann8 UI 1.12.13

ALT-Scann8.py
* Fix exception when capturing to DNG
=> ALT-Scann8 UI 1.12.14

ALT-Scann8.py
* Fix bug when capturing to PNG
* Same json file formatted
* Add last check date to configuration
=> ALT-Scann8 UI 1.12.16

ALT-Scann8.py
* Add Menu bar (mainly with help links)
=> ALT-Scann8 UI 1.12.17

ALT-Scann8.py
* Bugfix: When starting for teh first time (withotu ALT-Scann8.json file) target folder was not initialized after setting the base folder in the settings popup.
* Bugfixes: False misaligned frames alerts
=> ALT-Scann8 UI 1.12.20

FrameAlignmentChecker.py
* Align alignement detection algorithm with ALT-Scann8
* Fix but when clicking with middle mouse button to get file path (now copied to clipboard)
=> FrameAlignmentChecker 1.0.7

FrameAlignmentChecker.py
* Hardcode horizontal position of vertical detection stripe to 30 pixels
* Implement multiple threshold attempts on detection algorithm (as in AfterScan)
* Generate historic file with the overall % of bad frames (to compare different captures)
=> FrameAlignmentChecker 1.0.8

FrameAlignmentChecker.py, FrameChecker.py
FrameAlignmentChecker 1.0.10
* Add canvas to display detected bad alignements
* Improve misalignment detection
* Factorize code to load an ddisplay images (in UI and popup)
* Allow moving through the bad frame list + update images accordingly (color or B&W)
=> FrameAlignmentChecker 1.0.10 -> FrameChecker 1.0.10

ALT-Scann8.py
Fix issued when savign in PNG and DNG format
=> ALT-Scann8 1.20.2

ALT-Scann8-Controller.ino
New no film detection, based on traction switch
Idea to use traction switch from  Marco Robustini, adapted to existing code
=> ALT-Scann8-Controller 1.1.10

ALT-Scann8-Controller.ino, ALT-Scann8.py
- Add file save menu (By Marco Robustini)
- Corrected end of film detection for VFD ALT-Scann8-Controller 1.1.11
- Fallback to PT based film detection. Problem causing it to not work in VFD mode fixed.
=> ALT-Scann8 1.20.07
