jareff-g/ALT-Scann8

- ALT-Scann8-Controller.ino
- ALT-Scann8-UserInterface.py
- UI: When in automated mode, set spinboxes for PTLevel and Steps/Frame as 'readonly' instead of 'disabled', for better visibility
- Controller
- Adapt film collect speed when increasing scan speed (will need further refinement)
- Even when not set as automated, automatic steps/frame value was still calculated and applied
- During the speed reduction when about to detect a frame, sometimes a very wrong value was produced. Generate an error in such case to stop the scanning process (until issue is identified)
> Speed control bugfixes

- ALT-Scann8-Controller.ino
- ALT-Scann8-UserInterface.py
It seems the big part of the I2C cleanup code was somehow delivered to master while I tried to merge latest changes in master (ScanSpeed bugfixes) in I2C_Cleanup branch. It seems changes were done in both directions (for now, not missing anything). So, what is being merged here are some final changes in the I2C cleanup code, plus some bugfixes (some unrelated to I2C):
- While automatic mode enabled, spinboxes for Steps/Frame and PT Level are set as 'readonly' instead of disabled (better legibility)
- On RPi UI, add delays of 100µs before and after sending data to Arduino to avoid (or minimize at least) I/O errors (collisions might happen due to the asynchronous nature of the communication between both)
- Revert max speed delay to 500 µs (250 µs is too fast)
- No need to set MinFrameStps …
> I2c cleanup

- ALT-Scann8-Controller.ino
- ALT-Scann8-Pico-Controller.c
- ALT-Scann8-UserInterface.py
Still experimental, the objective is to better handle films with damaged sproket holes.
- Boosted threshold increases the PT threshold (in automatic mode) to 90% (better detectino fo frames when holes are broken)
- Added one extra button to manual scan feature so that film can be advance by either 5 or 20 steps
> 'Manual scan' changed to 'Damaged film'

- ALT-Scann8-Controller.ino
- ALT-Scann8-Pico-Controller.c
- ALT-Scann8-UserInterface.py
- Split 'Fine tune' into two new values:
- 'Auto PT Threshold': Set automatic PT Threshold between 5% to 95% (of difference between min and max PT values)
- Extra steps: Perform between 0 and 20 extra steps after frame has been detected
- Remove 'Boosted threshold' in experimental area (same can be achieved by setting 'Auto PT Threshold' to 90%)
> Frame align review

- ALT-Scann8-Controller.ino
- ALT-Scann8-UserInterface.py
- Disk space is now monitored during scan. If less than 500MB remain, scan process stops, to allow doing some cleanup, and prevent app crashing, and losing progress. This brings an additional dependency ('psutil'), that needs to be installed in your PC
- Couple of changes in Arduino
- Reels are now unlocked by default, they are engage only when needed. 'Unlock reels' is retained for now, but the idea is to remove it since it should not be useful any more
- New button to perform 'slow backward'. This is only available in experimental mode since it requires manual operation (reel A needs to be moved manually to collect outgoing film). Can be useful in some situations, as I found myself manually moving the capstan back to go back to a frame already passed by
> Disk space control + Arduino changes

- ALT-Scann8-Controller.ino
- ALT-Scann8-UserInterface.py
Arduino 1.0.5
- Extra steps can now be set to negative values (-30 to +30). When negative, they are subtracted from the minimum number of steps where Arduino will start considering the photo-transistor, if positive is still the same, unconditional number os steps are done after frame is detected, before snapshot is taken. Normally negative values shoudl not be needed, but today I had a weird case where even after physically adjusting the film gate position, frames were being detected too high. Need to check the scanner to see if there is something wrong. But then, it was the second movie of the day, and the first went perfectly fine (it had the same characteristics as the one with the problem)
> ALT-Scann8 1.8.46

- ALT-Scann8-Controller.ino
- ALT-Scann8-UserInterface.py
- tooltip.py
**Main changes in ALT-Scann8 1.9.0**
- Replace 'HQ' button with drop down with different resolutions (although minimum captor in HQ camera is always "2028x1520" at the minimum, so no speed gain
- Replace file type (jpg/png) radio buttons with drop down
- Add line with threshold level to integrated plotter
- Extra steps can now be set to negative values (-30 to +30). When negative, they are subtracted from the minimum number of steps where Arduino will start considering the photo-transistor, if positive is still the same, unconditional number os steps are done after frame is detected, before snapshot is taken. Normally, if extra steps needs to be used, it means there is something wrong elsewhere.
- HDR merge-in-place (Raspberry Pi does the merge after the capture). Works, but unpractical …
> ALT-Scann8 1.9.0

- ALT-Scann8-Controller.ino
- ALT-Scann8-UserInterface.py
- tooltip.py
* ALT-Scann8 1.8.40 (#59)
- HDR merge-in-place now works. But, as anticipated, is too slow (around 11 FPM, vs 36 FPM without). Rough extrapolation for RPi5 (x2.5 RPi4) would be 27 FPM, faster but still slow
* ALT-Scann8 1.8.41 (#61)
- Review of alignment of widgets, make them more evenly distributed, also in small screen mode
* ALT-Scann8 1.8.42 (#62)
- Fix some remaining alignment issues
- Display popup warning when running out of disk space
- Add disk space check to simulated capture loop (to test new popup)
* ALT-Scann8 1.8.43 (#63)
- Errors when starting in experimental or expert mode alone (only working when using both together)
* ALT-Scann8 1.8.43 (#64)
Arduino 1.0.3
- Bugfix for slow forward auto-stop. UV Led was switched off, so film detection could not work
* Plotter threshold …
> ALT-Scann8 1.9.0 (#68)

- ALT-Scann8-Controller.ino
- ALT-Scann8-UserInterface.py
- In the integrated plotter,display as well the minimum value Arduino 1.0.6:
- Improvement for frame alignment in special cases (films overexposed in the sprocket hole area, so that film is mostly transparent, causing PT levels to remin quite high with small variations). More aggressive PT automatic threshold is allowed. It is calculated as the middle point level of dynamic max/mit PT values, converging towards each other. Converging step is changed from 2 to 10 (faster convergence, so faster adaptation of threshold to current PT values)
- In Auto PT level mode, calculate the PT threshold only when the minimum steps per frame is reached, there is no use in doing it before, and also it was creating ugly bumps in the plotter graph that were making interpretation difficult
> ALT-Scann8 1.9.1

- ALT-Scann8-Controller.ino
- ALT-Scann8-UserInterface.py
- Final fixes for automatic scanner stop when end of film detected
- Alternate method for automatic stop: Instead of detecting end of film, it will stop when the 'frames-to-go' counter reaches zero
> Bugfix 2024 02 09

- ALT-Scann8-UserInterface.py
- Normalize handling of values from widgets
- Use the correct variable type (IntVar, DoubleVar, StringVar)
- Add validation functions
- Remove all useless convestions string to number
- Not directly related, but exposure field not is displayed using milliseconds (before it was an invented conversion)
- Bugfix: Sometimes there were errors while exiting the application due to pending 'after' callbacks. Now flag is added to indicate app is exiting to allow them to die gracefully (this implies a 3 seconds delay to give enough time to terminate).
> Review handling of values from widgets

- ALT-Scann8-UserInterface.py
- Improved field validation. Now values entered via keyboard are validated, and highlighted in red if not inside the correct range. they will become back once the value is correct. When scanning is active, value input via keyboard is disabled, to avoid disrupting the scan process (but some values can still be modified using arrow keys as before).
- Bugfixes
- Sharpness value was handled by the UI but never set at camera level, except at init time (so always 1)
- Set exposure at camera after configuration read
> ALT-Scann8 1.9.20

- ALT-Scann8-UserInterface.py
- Fix 'new folder' button (it had some problems and inconsistencies). Ideally it should be removed but TKInter does not allow to create a folder in the folder selection dialog.
- Fix bug when canceling after selecting 'new' folder button
- Prevent spinboxes from being modified with arrow keys when they are read only (they can still be changed via widget controls)
- Add a 5 sec delay before starting count down on 'frames to go' entry to allow user enough time to type the number
- Replace toggle buttons used in spinboxes with automatic mode by real checkboxes. Also merge the four white balance checkboxes (auto/wait delay) into two 
- Set background color of spinboxes to light green when in automatic mode
- Align labels of spinboxes 
- Set spinboxes background when readonly to 'pale green'
> ALT-Scann8 1.9.23

- ALT-Scann8-UserInterface.py
- Improve automatic exposure by integrating additional PiCamera2 controls
- Use correct control to set automatic exposure (AeEnable), vs ExposureTime = 0 (from legacy PiCamera)
- Move statistics frame to left column (as we might need to add more controls to expert area)
- Added in UI 8 new PiCam2 controls: AeConstraintMode, AeMeteringMode, AeExposureMode, Brightness, Contrast, Saturation, AnalogueGain, ExposureValue (auto exposure compensation)
- Fixed widget enable/disable based on status of other widgets
- Added widget-specific default value to validation/normalize functions, to use when value is invalid or empty
> ALT-Scann8 1.9.36 - Aec agc picamera2 controls

- ALT-Scann8-UserInterface.py
- Fix: go_disable_tooptips not initialized
> ALT-Scann8 1.10.3

- ALT-Scann8-UserInterface.py
- Bugfix: 'AWB Mode' control was enabled/disabled based on AE, instead of AWB. Corrected.
- Automatic calculation of font size depending on screen size
- Keep manual WB values separated from AWB calculated ones
- Control widgets enabled while scanning by default. Opposite behavior with -w
- Refresh AE/AWB values as per 'preview module' setting
- Enforce preview module in all use cases
> ALT-Scann8 1.10.17

- ALT-Scann8-Controller.ino
- ALT-Scann8-UserInterface.py
Main changes commits 11-19 March (ALT-Scann 1.10.25-44)
- Add new option to settings: 'Color coded buttons' to highlight buttons with specific colors when active
- Move Fahrenheit checkbox to settings menu
- Move resolution / file type dropdowns to 'settings' dialog
- Refactor coe to handle status of widgets dependign on other widgets
- Adjust some font sizes to make them more readable (scanned frames, frames to go, target folder)
- Add dedicated persisted option for automatic exposure (vs exposure=0 before)
- When scanning, display FPS instead of FPM
- Merge exposure/WB 'match wait' checkboxes in a single one
- Only manual Exp/WB values are persisted in session data, not automatic ones
- Arduino 1.0.20: Rwnd/FF with film in film gate, fixed Film-in-filmgate protection, broken dua to …
> ALT-Scann8 1.10.44

- ALT-Scann8-UserInterface.py
- Bugfix - Issue in simulated mode
- Adjust widget positions in 'Settings' popup window
- Do not allow to set a non-existing folder as base folder
- Do not allow to start simulated scan session from a folder with no captured frames
- Set 'Settings' button at the bottom of teh top left area of main window
- Make S8/R8 buttons dill the frame they are in
- Add 'ms' label after exposure spinbox
- Fix resolution not saved
- Rename 'session' and 'persisted' to configuration in preparation to split configuration data from session data
- Save and restore position of popup window
- Separate session data from config data. Session data includes:
- Negative image
- Film Type
- Scanned frames
- Pending frames
- File type
- Target directory
- Capture resolution
- HDR Active
- HDR settings
> ALT-Scann8 1.10.50

- ALT-Scann8-UserInterface.py
Fix default value of frame fine tune at startup (set to 20, but saved as 50 if no other changes are done)
> ALT-Scann8 user interface 1.10.75

- ALT-Scann8-Controller.ino
- ALT-Scann8-UserInterface.py
- Move log files to dedicated subfolder ('Logs')
- Add scan error counter in UI (number of steps required to detect frame differ more than 20% from value calculated based on capstan diameter)
- Add separate log file for scan errors (''ScanErrors.YYYYMMDD.log) containing frames that failed the check, along with the number of steps done to detect it
> ALT-Scann8 user interface 1.11.5, ALT-Scann8 controller 1.1.3

- FrameAlignmentChecker.py
ALT-Scann8 User Interface 1.11.9
* Move 'scan errors' counter to Frame align section, also rename to 'frame errors'
ALT-Scann8 User Interface 1.11.10
* Change width taken by some widgets to prevent lower control area to be wider than upper
ALT-Scann8 User Interface 1.11.11
* For existing config files, transform legacy name CentreWeighted to CentreWgt
ALT-Scann8 User Interface 1.11.12
* Remove test data from UI after latest changes
ALT-Scann8 User Interface 1.11.13
* Check frame misalignment also in DNG files (**Untested**)
* This feature requires a couple of libraries (rawpy, imageio) which have to be installed via pip, which I prefer not to do in my system. If you give it a try and it works, let me know and I'll remove the warning.   
* Fix bug when initializing widget when HDR Auto …
> Merging latest changes from develop

- ALT-Scann8-UserInterface.py
- FrameAlignmentChecker.py
ALT-Scann8 User Interface 1.11.17 
* Enable frame alignment checking for DNG files
* This feature requires using the rawpy library, for which and I have not found a (simple) way to install it at system level in the Raspberry Pi, so needs to be installed using a python virtual environment. Here are the steps to do so:
* python -m venv --system-site-packages altscann8 # Creates a virtual environment named 'altscann8'. 'system-site-packages' is to allow the venv to access packages installed at system level
* source altscann8/bin/activate # Activates the virtual environment just created
* pip install rawpy # Install the rawpy library, required to handle DNG files in python 
* pip install numpy==1.26.4 # Required as when installing rawpy, pip will install a newer version of numpy that is not …
> Add DNG support - ALT-Scann8 User Interface 1.11.17, FrameAlignmentChecker 1.0.6

- ALT-Scann8-UserInterface.py
- FrameAlignmentChecker.py
ALT-Scann8 User Interface 1.11.17 
* Enable frame alignment checking for DNG files
* This feature requires using the rawpy library, for which and I have not found a (simple) way to install it at system level in the Raspberry Pi, so needs to be installed using a python virtual environment. Here are the steps to do so:
* python -m venv --system-site-packages altscann8 # Creates a virtual environment named 'altscann8'. 'system-site-packages' is to allow the venv to access packages installed at system level
* source altscann8/bin/activate # Activates the virtual environment just created
* pip install rawpy # Install the rawpy library, required to handle DNG files in python 
* pip install numpy==1.26.4 # Required as when installing rawpy, pip will install a newer version of numpy that is not …
> Add DNG frame check support - ALT-Scann8 User Interface 1.11.17, FrameAlignmentChecker 1.0.6

- ALT-Scann8.py
The "focus assist" it is a simple filter based on edge detection (in this case I used the Sobel operator), which puts the parts of the image where the local contrast is maximum in red.
Basically, these high-contrast areas (i.e., where there is a marked edge between two regions-for example, the outline of a film, negative textures, or sharp details) correspond to the points in the frame that are in focus.
When the subject is blurred, the edges “soften”: the gradient histogram becomes all “low” because there are no sharp light/dark pixel transitions.
As a result, almost no gradient value exceeds the threshold the mask mask will be almost all black.
In practice, if the focus ring is too far forward or too far back, you will see very few or no red pixels.
The more the scene is “off-focus,” …
> Focus assist
